### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by deckerst** [dart-lang/leak_tracker#154]
I wanted to give this package a try and did the following:
1) added `leak_tracker` to pubspec (resolving to leak_tracker v9.0.6),
2) added the following before `runApp`:
```dart
  LeakTracking.start();
  MemoryAllocations.instance.addListener(
    (event) => LeakTracking.dispatchObjectEvent(event.toMap()),
  );
```
which is __not__ what's in README, but which is in the minimal example,
3) launched my app in debug mode on a real device,
4) opened DevTools (v2.25.0) > `Memory` tab > `Detect Leaks` tab (where I see several leak detection logs),
5) pressed `Analyze and Download`.

It fails with the following feedback: `Error: TypeError: Instance of 'minified:JP': type 'minified:JP' is not a subtype of type 'minified:GP'`

And for what it's worth, I also see in the browser dev console the following log (when launching DevTools, but I don't know whether it's related to the issue here):
`Attempted to call extension 'ext.flutter.inspector.structuredErrors', but no service with that name exists`

Using Flutter Channel stable, 3.13.8, on Ubuntu 23.04 6.2.0-34-generic, locale en_GB.UTF-8.

Am I doing something wrong?

**Comment by polina-c** [comment]
Thank you for your question.

At the moment the package is unstable and is work in progress. Our first priority is to clean up memory leaks in Flutter Framework and enable regression testing for leaks.

This is how you can help to enable it faster:

1. Vote here: https://github.com/flutter/devtools/issues/6266#issuecomment-1758474605
2. Contribute here: https://github.com/flutter/flutter/issues/137311

Does it help?

**Comment by deckerst** [comment]
Actually I've already used the package and it helped me fix many leaks, but I was curious about the integration in DevTools. Thanks for working on this!

**Comment by polina-c** [comment]
Good to know! For integration with DevTools you can vote/comment here: https://github.com/dart-lang/leak_tracker/issues/172
