### ISSUE TITLE
Implement flutter version of `withLeakTracking` that calls `MemoryAllocations.instance.addListener`

### ISSUE THREAD

**Issue by JulianBissekkou** [dart-lang/leak_tracker#52]
To be able to catch flutter framework memory leaks we have to call `MemoryAllocations.instance.addListener` which does not happen in `withLeakTracking`.
I understand if `withLeakTracking` should be framework independent but then we should update the documentation 👍🏽

**Comment by polina-c** [comment]
Discussion: https://github.com/flutter/devtools/issues/3951#issuecomment-1588046913
