### ISSUE TITLE
update readme with more information

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/leak_tracker#78]
Now that this package is published, we should update the readme with a bit more information:

- what's the package? what's it used for?
- a (brief) code example?
- references to more comprehensive documentation

cc @polina-c

**Comment by polina-c** [comment]
The package is still under construction and is constantly changing.
It is published for internal use only for now.
As soon as the package stabilizes, I will update readme. 

This task is tracked under https://github.com/flutter/devtools/issues/3951

So, closing this issue as duplicate

**Comment by devoncarew** [comment]
> It is published for internal use only for now. 

Gotcha, understood. FYI, I updated the status at https://pub.dev/packages/leak_tracker/admin to 'unlisted'; that means the package will not show on pub.dev search results. You can toggle that back at any time once this package is meant to be more visible.

**Comment by devoncarew** [comment]
We should update the readme with the info in the first comment (for both packages leak_tracker and leak_tracker_testing). They're both published, in tools.dart.dev, and on non pre-release versions; we really need more than 'coming soon'.
