### ISSUE TITLE
changelog contains entries for several unpublished versions

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/leak_tracker#79]
Hi - it looks like the changelog has entries for several unpublished package versions:

https://github.com/dart-lang/leak_tracker/blob/main/CHANGELOG.md

The last published version of the package was `6.0.0`; everything after that (the entries for 6.0.1 - 7.0.4) should be accumulated in a new, unpublished entry - with a `-wip` suffix for the versions - and that version changed to a stable release when we're ready for the next publish. So - if we have had a breaking api change - the current pubspec+changelog entry should be something like `7.0.0-wip`.

This wiki has some info on the general versioning + publishing process and rational: https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance.

**Comment by polina-c** [comment]
Fixed
